### ISSUE TITLE
运行时出现以下报错

### ISSUE THREAD

**Issue by Sciroccogti** [OYMiss/forward-bot#1]
```Linux
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5409369be0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /【bot token】/deleteWebhook
ERROR:telegram.ext.updater:Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /【bot token】/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f5409369dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING:telegram.ext.updater:Failed bootstrap phase; try=10 max_retries=-1
```

**Comment by OYMiss** [comment]
如果代理的地址和端口都正确的话，考虑使用 socks5h://127.0.0.1:1080/  试一下。

**Comment by Sciroccogti** [comment]
```Linux
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff645be0b38>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5700): Max retries exceeded with url: /_get_friend_list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff645be0b38>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    run()
  File "main.py", line 116, in run
    coolq_bot = CoolQBot(forward_bot)
  File "/home/ubuntu/forward-bot/coolq_bot/coolq_bot.py", line 20, in __init__
    self.refresh()
  File "/home/ubuntu/forward-bot/coolq_bot/coolq_bot.py", line 45, in refresh
    self.__init_friends()
  File "/home/ubuntu/forward-bot/coolq_bot/coolq_bot.py", line 49, in __init_friends
    for group in self.coolq_bot._get_friend_list():
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cqhttp/__init__.py", line 20, in do_call
    resp = requests.post(url, json=kwargs, headers=headers)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5700): Max retries exceeded with url: /_get_friend_list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff645be0b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

同时，酷Q有以下日志
<img width="413" alt="image" src="https://user-images.githubusercontent.com/32357397/50341691-c3b31600-055a-11e9-872f-7693a3d7676a.png">

??? Q ???? data\app\io.github.richardchien.coolqhttpapi\log\ ???????

另外，注意到我已经将cqhttp_host和socks5的链接都改为78.188.218.10，但报错中仍有原链接

**Comment by OYMiss** [comment]
coolq 应该不需要代理，问题可能是 _get_friend_list 这个接口。
我以前遇到这个问题的时候，docker 关了，把 coolq 那个文件夹删了，重新开下 docker 就行了。
（应该不需要删整个 coolq ，但是简单暴力，我就全删了）。
希望对你有用。

**Comment by OYMiss** [comment]
由于程序是自己写着玩的，没想那么多，[此处代码](https://github.com/OYMiss/forward-bot/blob/ae617307d0b2f29869c039fee554de6a92cbc9bd/coolq_bot/coolq_bot.py#L8) 我就直接写死是 `host='127.0.0.1', port=5700`。
